### ISSUE TITLE
node selection not shown in network when clicking between different clouds unless you click on zoom or pan buttons

### ISSUE THREAD

**Issue by risserlin** [BaderLab/WordCloudPlugin#10]
not sure if this is a cytoscape thing or associated with the app.  After creating multiple clouds if you go back to a previous cloud the word cloud panel updates but the selection of the nodes associated with the cloud doesnot get highlighted.  (if you press the + or - or zoom then the nodes the yellow selection shows up.)

**Comment by jrrmzz** [comment]
This is a bug.  We need to tell Cytoscape to redraw when we adjust the selection.
