### ISSUE TITLE
Change default attribute selection to node name

### ISSUE THREAD

**Issue by risserlin** [BaderLab/WordCloudPlugin#11]
When a cloud is created it defaults to use all of the node attributes for the given selection.  Can we change that to just node shared.name and allow the user to add columns if they want.

**Comment by jrrmzz** [comment]
This was the old behaviour but it was problematic for a number of networks.  Usually, the shared_name column has a bunch of unique IDs.  When you have a cloud where all words have the same frequency, the resulting font sizes are undefined and nothing shows up.  So it looks like WordCloud just doesn't work.  If users want to deselect everything and pick their own columns, there's a "deselect all" option in the attribute list.  Is that a fair compromise?

**Comment by mikekucera** [comment]
Yes it is
