### ISSUE TITLE
tried to have a session (with no word cloud in it but word cloud is an installed app) - get weird error

### ISSUE THREAD

**Issue by risserlin** [BaderLab/WordCloudPlugin#12]
![image](https://cloud.githubusercontent.com/assets/3842763/3072646/abfeee0a-e2cb-11e3-8eee-924a94262fc2.png)
when trying to resave a stored session (no wordclouds in it and word cloud not used at all) I get the above error

**Comment by mikekucera** [comment]
Can't reproduce this, please reopen if it happens again.
