### ISSUE TITLE
Building clouds off of list attributes

### ISSUE THREAD

**Issue by risserlin** [BaderLab/WordCloudPlugin#32]
Not sure if this is a bug or possibly a use case not accounted for.  
I have a single node and the node contains a list attribute of all the publications associated with the node.  I want to create a cloud from that attribute but the when i do I can see all the words contained in the attribute but they are all the same size and in one cluster.

If I try and move the normalization bar the cloud disappears completely.

**Comment by mikekucera** [comment]
I caused this problem when I rewrote the word parsing. The parser returns a Set, so if the same word is used in the same attribute value multiple times it only gets counted once. This problem is not specific to list attributes.
