### ISSUE TITLE
How do I change the name of a created cloud?

### ISSUE THREAD

**Issue by risserlin** [BaderLab/WordCloudPlugin#33]
I tried right clicking on the cloud but that didn't work.

**Comment by mikekucera** [comment]
That should work. When I right click on a cloud in the list the popup menu includes "rename cloud".

**Comment by mikekucera** [comment]
I'm going to close this. Please reopen if the problem comes back.

**Comment by risserlin** [comment]
There is no right click context menu on the cloud on windows.
