### ISSUE TITLE
Word count cutoff

### ISSUE THREAD

**Issue by risserlin** [BaderLab/WordCloudPlugin#35]
Lots of words that only appear once or twice end up cluttering the cloud.  Having a parameter where we can filer those out would be useful.

Either we can filter by absolute counts i.e. any word that only appears X or less times or by word count distribution elimianting words that appear in the bottom X%.

**Comment by mikekucera** [comment]
I added the ability to filter out by an absolute count. I think this is easier to understand and to predict its behaviour.
